export const GET_PRODUCT = "GET_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const RETRIEVE_PRODUCTS = "RETRIEVE_PRODUCTS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";

export const RETRIEVE_PRODUCTS_DB = "RETRIEVE_PRODUCTS_DB";

export const GET_INVOICE = "GET_INVOICE";
export const ADD_INVOICE = "ADD_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";
export const RETRIEVE_INVOICES = "RETRIEVE_INVOICES";
export const SEARCH_INVOICE = "SEARCH_INVOICE";

export const RETRIEVE_HISTORY_PRODUCT = "RETRIEVE_HISTORY_PRODUCT";

export const GET_REVENUE = "GET_REVENUE";
export const GET_EXPENDITURE = "GET_EXPENDITURE";

export const GET_LIST_REVENUE = "GET_LIST_REVENUE";
export const GET_LIST_EXPENDITURE = "GET_LIST_EXPENDITURE";

export const GET_LIST_IMPORT_PRODUCT = "GET_LIST_IMPORT_PRODUCT";
export const GET_LIST_EXPORT_PRODUCT = "GET_LIST_EXPORT_PRODUCT";

